- name: Install Docker on app servers
  hosts: app
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started

- name: Install and start Postgresql on database servers
  hosts: database
  become: true

  vars:
    postgres_version: "12"
    data_directory: "/var/lib/postgresql/{{ postgres_version }}/main"

  tasks:
    - name: Install Postgresql dependencies
      apt:
        name:
          - postgresql-{{ postgres_version }}
          - postgresql-client-{{ postgres_version }}
          - postgresql-contrib-{{ postgres_version }}

    - name: Create data directory
      file:
        path: "{{ data_directory }}"
        state: directory
        owner: postgres
        group: postgres
        mode: "0700"

    - name: Initialize database cluster
      command: /usr/lib/postgresql/{{ postgres_version }}/bin/initdb -D "{{ data_directory }}"

    - name: Start Postgresql service
      service:
        name: postgresql
        state: started
